### ISSUE TITLE
How to customize which email should receive the otp

### ISSUE THREAD

**Issue by Fanom2813** [afsakar/filament-otp-login#14]
### What happened?

this is not a bug , but how can i customize which email is receiving the OTP, i have tried to use the custom login but it doesn't seem to take effect i donno if it is caching problem.

### How to reproduce the bug
<img width="1077" alt="Screenshot 2024-11-01 at 9 30 49 AM" src="https://github.com/user-attachments/assets/c3b1c185-6c94-49f1-a4ac-f9a0c898129b">

when i use custom login and i run `php artisan optimize`

### Package Version

1.3.6

### PHP Version

8.3

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have modified the `Login` class to allow customization of the email receiving the OTP. I've added a new method `getOtpEmail()` which can be overridden in a custom login page to specify a different email for OTP. I've also updated the `sendOtpToUser()` method to use this new method.

Here's a summary of the changes:

1. Added a new `getOtpEmail()` method.
2. Modified `sendOtpToUser()` to use `getOtpEmail()`.
3. Updated `generateCode()` to use `getOtpEmail()`.
4. Updated `verifyCode()` to use `getOtpEmail()`.

These changes allow for more flexibility in determining which email receives the OTP, while maintaining backwards compatibility with the existing implementation.

I also created pull request: https://github.com/afsakar/filament-otp-login/pull/15


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by afsakar** [comment]
Hi, sorry I don't understand exactly where the problem is. Can you share your OverrideLogin page? So I can understand exactly what the problem is and why you feel the need to make this change. Also, if ‘this is not a bug’ then you can omit the ‘bug’ tag :)

**Comment by Fanom2813** [comment]
i copied the exact example you have provided in the documentation

**Comment by afsakar** [comment]
Can you show me the code? Everything works good in my codebase.
